spring:
  application:
    name: account-ui
  redis:
    host: localhost
    port: 6379
    database: 0

server:
  port: 8081
demo:
  account-service:
    topic: accounts
    url: http://localhost:8080
