spring:
  application:
    name: account-ui
  redis:
    host: localhost
    port: 6379
    database: 0

server:
  port: 8081

hystrix:
  metrics:
    enabled: false

demo:
  ui:
    account-service:
        topic: accounts
        url: http://localhost:8080
    stomp:
      topic: /topic/greetings
      url: ws://localhost:8081/gs-guide-websocket
