spring:
  application:
    name: account-ui
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: 0

server:
  port: ${PORT:8081}

hystrix:
  metrics:
    enabled: false


demo:
  ui:
    account-service:
      url: ${ACCOUNT_SERVICE_URL:http://localhost:8080}
